package com.myemohealth.e2e.tests;

import com.myemohealth.e2e.pages.LoginPage;
import com.myemohealth.e2e.pages.QcmPage;
import com.myemohealth.e2e.pages.SidebarPage;
import com.myemohealth.e2e.pages.SignupPage;
import io.github.bonigarcia.wdm.WebDriverManager;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.support.ui.ExpectedConditions;

import java.time.Duration;

public class AdvancedFlowTest {

    private WebDriver driver;
    private WebDriverWait wait;
    private LoginPage loginPage;
    private QcmPage qcmPage;
    private SignupPage signupPage;
    private SidebarPage sidebarPage;

    private static final String LOGIN_URL = "http://localhost:4200/login";

    @BeforeEach
    public void setUp() {
        WebDriverManager.chromedriver().setup();
        ChromeOptions options = new ChromeOptions();
        // options.addArguments("--headless");
        // options.addArguments("--disable-gpu");
        driver = new ChromeDriver(options);
        driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(5));
        driver.manage().window().maximize();
        wait = new WebDriverWait(driver, Duration.ofSeconds(10));

        loginPage = new LoginPage(driver);
        qcmPage = new QcmPage(driver);
        signupPage = new SignupPage(driver);
        sidebarPage = new SidebarPage(driver);
    }

    @Test
    public void testQcmCreationFlow() {
        driver.get(LOGIN_URL);
        // Login as specific user requested
        loginPage.login("newuser_1766693388790@example.com", "securePassword123");

        try {
            // Wait for session to stabilize as requested
            Thread.sleep(2000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }

        // Navigate to QCMs (Assuming sidebar has QCM link or direct URL)
        driver.get("http://localhost:4200/qcms");

        String templateTitle = "E2E Stress Test " + System.currentTimeMillis();

        // Create Template
        qcmPage.clickCreateTemplate();
        qcmPage.fillTemplateForm(templateTitle, "Generated by E2E Automation");
        qcmPage.submitTemplate();

        // Verify Template Created
        // Assertions.assertTrue(qcmPage.isTemplatePresent(templateTitle), "New template
        // should appear in list");

        // Add Questions (Dialog opens automatically after creation)
        // qcmPage.openQuestionsForTemplate(templateTitle); // Removed as automatic

        String questionText = "How are you feeling today?";
        String alertText = qcmPage.addQuestion(questionText);

        // Verify Question Added via Alert Message
        Assertions.assertEquals("Question created successfully!", alertText, "Success alert should appear");
    }

    @Test
    public void testSignupFlow() {
        // Start from Login Page
        driver.get(LOGIN_URL);

        // Navigate to Signup via Link
        loginPage.clickSignupLink();

        // Ensure we are on register page
        wait.until(ExpectedConditions.urlContains("register"));

        String newEmail = "newuser_" + System.currentTimeMillis() + "@example.com";
        // Using valid password > 8 chars as requested
        signupPage.register("New", "User", newEmail, "securePassword123", "PATIENT");

        // Verify Redirect to Login
        Assertions.assertTrue(signupPage.isRegistrationSuccessful(), "Should redirect to login after signup");

        // Verify login with new user
        loginPage.login(newEmail, "securePassword123");
        // Check finding dashboard/sidebar
        Assertions.assertTrue(sidebarPage.isUserProfileVisible(), "New user should be able to login");
    }

    @AfterEach
    public void tearDown() {
        if (driver != null) {
            driver.quit();
        }
    }
}
